name: chat-steward
version: 0.1.1
summary: Chatbot written in Go for Jupiter Broadcasting
description: |
  https://gitlab.com/Kpovoc/chat-steward

grade: devel
confinement: strict

apps:
  chat-steward:
    command: bin/chat-steward --userdata "$SNAP_USER_COMMON" --resources "$SNAP/resources"
    plugs:
      - network
      - network-bind

parts:
  go:
    source-tag: go1.10.2
  chat-steward:
    after: [go]
    source: .
    plugin: go
    go-importpath: gitlab.com/Kpovoc/chat-steward
    install: |
      cp -a resources $SNAPCRAFT_PART_INSTALL/resources
