name: chat-steward
version: 0.2.0
summary: Chatbot written in Go for Jupiter Broadcasting
description: |
  https://gitlab.com/Kpovoc/chat-steward

grade: devel
confinement: strict

apps:
  chat-steward:
    command: bin/chat-steward --userdata "$SNAP_USER_COMMON" --resources "$SNAP/resources"
    plugs:
      - network
      - network-bind

parts:
  go:
    source-tag: go1.11
  chat-steward:
    after: [go]
    source: .
    plugin: go
    go-importpath: gitlab.com/Kpovoc/chat-steward
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/resources
      cp -a web $SNAPCRAFT_PART_INSTALL/resources/
