name: chat-steward
version: 0.2.2
summary: Chatbot written in Go for Jupiter Broadcasting
description: |
  https://gitlab.com/Kpovoc/chat-steward

grade: devel
confinement: strict
base: core20

apps:
  chat-steward:
    command: bin/chat-steward --userdata $SNAP_USER_COMMON --resources $SNAP/resources
    plugs:
      - network
      - network-bind

parts:
  chat-steward:
    source: .
    plugin: go
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/resources
      cp -a web $SNAPCRAFT_PART_INSTALL/resources/